### ISSUE TITLE
Product name container parent class is undefined

### ISSUE THREAD

**Issue by JNussens** [vtex-apps/product-summary#225]
The parent of productNameContainer is coming as "undefined", it should come as every other class
## Expected Behavior

The parent of productNameContainer is coming as "undefined", it should come as every other class

## Current Behavior

The parent of productNameContainer is coming as "undefined", it should come as every other class

## Steps to Reproduce (for bugs)

1. Create a shelf containing the product-summary, as below:
```
"shelf#home": {
    "blocks": ["product-summary#home"],
    "props": {
      "orderBy": "OrderByTopSaleDESC",
      "paginationDotsVisibility": false,
      "skusFilter": "FIRST_AVAILABLE",
      "productList": {
        "maxItems": 10,
        "itemsPerPage": 4,
        "minItemsPerPage": 1,
        "scroll": "BY_PAGE",
        "arrows": true,
        "titleText": "Must have"
      }
    }
  },

  "product-summary#home": {
    "props": {
      "isOneClickBuy": false,
      "showBadge": false,
      "displayBuyButton": "displayButtonNone",
      "showCollections": false,
      "showListPrice": false,
      "showLabels": false,
      "hideBuyButton": true,
      "showInstallments": false,
      "showSavings": false,
      "priceAlignLeft": true,
      "name": {
        "showBrandName": false,
        "showSku": true,
        "showProductReference": false
      }
    }
  }
```
2. Add the shelf to the `store.home` blocks section.
3. The bug will display as follows:
<img width="1680" alt="Screen Shot 2020-01-10 at 01 35 24" src="https://user-images.githubusercontent.com/7662734/72126290-5e3eec80-334a-11ea-950c-66e2261fbc0b.png">

## Context

I can't remove the padding on the parent element of productNameContainer.

## Your Environment

* Version used: 2.x
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): 
* Link to your project: https://dev--miriadeit.myvtex.com/

**Comment by klzns** [comment]
Fixed! Thanks!
