### ISSUE TITLE
Bug with product-summary-sku-selector

### ISSUE THREAD

**Issue by stellinhastar** [vtex-apps/product-summary#269]
**Describe the bug**

When I use the product-summary-sku-selector in the gallery with ALL_AVAILABLE sku filter, the skus thats are out of stocks, appear as a empty sku

**To Reproduce**

https://skuselector--columbiacl.myvtex.com/hombre

**Expected behavior**

It would be best not to show the skus out of stock

**Screenshots**

![image](https://user-images.githubusercontent.com/54483907/87787865-bd5a4e00-c812-11ea-8c6c-828d81f5d7f9.png)

**Desktop environment:**

**Smartphone environment:**

**Additional context**

**Comment by denisebiscaro** [comment]
Fixed! https://github.com/vtex-apps/store-components/pull/828
