### ISSUE TITLE
How to change "Unavailable" Button text ?

### ISSUE THREAD

**Issue by hugocostadev** [vtex-apps/product-summary#281]
I'm trying to change the "unavailable" text from products that do not have stock. 
At my store that I'm working on, I need to change the text because that product has resellers at PDP and I want to change to "Learn more" for example, to induce the user to click to see the product itself.

**Comment by iago1501** [comment]
Hello @hugocostadev... we have a doc explaining about how can you do this
https://vtex.io/docs/recipes/development/overwriting-the-messages-app/

**Comment by hugocostadev** [comment]
Thanks for the reply @iago1501 , but I don't want to change at the entire website, I just want to change at "shelf" (product list) and "gallery" (search-result) if I modify the message itself will overwrite all "Unavailable" messages

**Comment by hugocostadev** [comment]
Any news?

**Comment by BlackBashi** [comment]
4 years later... Did you manage to solve this? @hugocostadev
