### ISSUE TITLE
Product-summary-image on mobile is broken when `hover` prop is selected

### ISSUE THREAD

**Issue by kid-three** [vtex-apps/product-summary#304]
**Describe the bug**
If product-summary-image has the `hover` prop on on, on mobile when you hold your finger to an image it tries to replicate the behavior on desktop, however the hover image is not rendered, so it shows a blank image

**To Reproduce**

open https://www.thenorthface.com.mx/hombre/chamarras-y-chalecos on any mobile device.
Press and hold on any product image, the image will go blank. 

You can also replicate this behavior on desktop if you open dev tools and select mobile view, unclick the finger incon and hover over any product image, it will disapear

**Expected behavior**
Nothing should change as hover does not exist on mobile

**Screenshots**
![Screen Shot 2021-03-30 at 21 19 50](https://user-images.githubusercontent.com/32473931/113085784-bb1c0200-919d-11eb-99aa-5b58273af583.png)

**Comment by ZusMexSideCorebiz** [comment]
Have you found any solution?
