### ISSUE TITLE
Create component Product Summary 

### ISSUE THREAD

**Issue by brunojdo** [vtex-apps/product-summary#8]
Create a component that contains Price, Image, NameProduct, and Promotion Badge components and use resolvers to get all data needed. 

## Expected Behavior

The product summary must use a card component of vtex styleguide and show a product and your information. The following properties must be editable: 

**Price**
- showListPrice: `boolean`
- showLabels: `boolean` _// Show labels "De" "Por"_
- showInstallments: `boolean` 

**Promotion Badge** 
- showBadge: `boolean`
- text: `String` *optional* 

**Buy Button** 
- hide: `boolean`
- showOnHover: `boolean`

**Comment by andreldsa** [comment]
Waiting for [buyButton#2](https://github.com/vtex-apps/buy-button/pull/2) and [ImageView#13](https://github.com/vtex-apps/product-summary/pull/13) completion.

**Comment by estacioneto** [comment]
Done
